# -*- coding: utf-8 -*-
"""Plivo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BTAF6YEsvQL87Bg3WieBlw3StZ4ey1Ul
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
uploaded = files.upload()

uploaded.keys()

!unzip pii_ner_assignment_IITB.zip -d .

!ls -R pii_ner_assignment_IITB

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/pii_ner_assignment_IITB
!pip install -r requirements.txt

!python src/train.py \
  --model_name distilbert-base-uncased \
  --train data/train.jsonl \
  --dev data/dev.jsonl \
  --out_dir out

!python src/predict.py \
  --model_dir out \
  --input data/dev.jsonl \
  --output out/dev_pred.json

!ls out

"""Evaluation"""

!python src/eval_span_f1.py \
  --gold data/dev.jsonl \
  --pred out/dev_pred.json

"""Predict Stress Set"""

!python src/predict.py \
  --model_dir out \
  --input data/stress.jsonl \
  --output out/stress_pred.json

"""Evaluate Stress"""

!python src/eval_span_f1.py \
  --gold data/stress.jsonl \
  --pred out/stress_pred.json

"""Measure latency"""

!python src/measure_latency.py \
  --model_dir out \
  --input data/dev.jsonl \
  --runs 50

"""Improving NER"""

# !python src/train.py \
#   --model_name bert-base-uncased \
#   --train data/train.jsonl \
#   --dev data/dev.jsonl \
#   --out_dir out2 \
#   --epochs 6 \
#   --batch_size 16 \
#   --lr 3e-5 \
#   --dropout 0.2
!python src/train.py \
  --model_name bert-base-uncased \
  --train data/train.jsonl \
  --dev data/dev.jsonl \
  --out_dir out2 \
  --epochs 6 \
  --batch_size 16 \
  --lr 3e-5

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/pii_ner_assignment_IITB

!ls src

!cat src/model.py

!python src/train.py \
  --model_name bert-base-uncased \
  --train data/train.jsonl \
  --dev data/dev.jsonl \
  --out_dir out2 \
  --epochs 6 \
  --batch_size 16 \
  --lr 3e-5

!python src/predict.py --model_dir out2 --input data/dev.jsonl --output out2/dev_pred.json
!python src/eval_span_f1.py --gold data/dev.jsonl --pred out2/dev_pred.json

!python src/predict.py --model_dir out2 --input data/stress.jsonl --output out2/stress_pred.json
!python src/eval_span_f1.py --gold data/stress.jsonl --pred out2/stress_pred.json

!python src/predict.py \
  --model_dir out2 \
  --input data/dev.jsonl \
  --output out2/dev_pred.json

!python src/eval_span_f1.py \
  --gold data/dev.jsonl \
  --pred out2/dev_pred.json

!python src/predict.py \
  --model_dir out2 \
  --input data/stress.jsonl \
  --output out2/stress_pred.json

!python src/eval_span_f1.py \
  --gold data/stress.jsonl \
  --pred out2/stress_pred.json

!python src/measure_latency.py \
  --model_dir out2 \
  --input data/dev.jsonl \
  --runs 50